# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aurelia's Kitchen
encoding: utf-8

email: svetla.kokalova@gmail.com.com
description: > # this means to ignore newlines until "baseurl:"
  Кулинарен блог за
  лесни и вкусни
  рецепти
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aurelias-kitchen.com" # the base hostname & protocol for your site

permalink: pretty


paginate: 11
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: 'http://aurelias-kitchen.com/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "hidden"
          value: "Aurelia"
      - name: "dsq_thread_id"
        field:
          element: "hidden"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Адрес на рецептата"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Дата"
          value: CURRENT_DATETIME
      - name: "Categories"
        field:
          element: "multiselect"
          label: "Категории"
          placeholder: "Избери една или повече категории"
          options:
            - name: "Закуски"
              value: "Breakfast"
            - name: "Десерти"
              value: "desserts"
            - name: "Напитки"
              value: "drinks"
            - name: "Основни"
              value: "main-courses"
            - name: "Разни"
              value: "others"
            - name: "Предястия"
              value: "starters"
      - name: "servings"
        field:
          element: "number"
          label: "Порции"
          value: ""
      - name: "calories"
        field:
          element: "number"
          label: "Калории (kCal)"
          value: ""
      - name: "preparation_time"
        field:
          element: "number"
          label: "Време за подготовка (в мин)"
          value: ""
      - name: "cooking_time"
        field:
          element: "number"
          label: "Време за готвене (в мин)"
          value: ""

# Gems
gems: [jekyll-paginate]
